### ISSUE TITLE
Memory leak when the ResultSet be closed

### ISSUE THREAD

**Issue by StefanXiepj** [datanucleus/datanucleus-api-jdo#106]
## What's about this pr?
Memory-leak happened in function of org.datanucleus.api.jdo.JDOPersistenceManager#retrieveAll(java.util.Collection, boolean)

## How it happened?
In this pr, when killed some process in mysql like:
```
mysql>show processlist;
mysql> kill "number from first col";
```
then, we find memory-leak happened because exception throwed from `i.next()`.
Code is like:
```
    public void retrieveAll(Collection pcs, boolean useFetchPlan)
    {
        assertIsOpen();
        ArrayList failures = new ArrayList();
        Iterator i = pcs.iterator();
        while (i.hasNext())
        {
            try
            {
                jdoRetrieve(i.next(), useFetchPlan);
            }
            catch (RuntimeException e)
            {
                failures.add(e);
            }
        }
        if (!failures.isEmpty())
        {
            throw new JDOUserException(Localiser.msg("010038"), (Exception[]) failures.toArray(new Exception[failures.size()]));
        }
    }
```
the iterator's size just is 40, but the size of failures is 17G, it's amazing...

![image](https://user-images.githubusercontent.com/26733114/103266966-adfb4580-49eb-11eb-8a40-276cc449fdbe.png)

When exception throwed from line 400 in QueryResultIterator.next(), but the nextRowNum do not add 1, it means the function of next() does not work.
![image](https://user-images.githubusercontent.com/26733114/103268267-2a8f2380-49ee-11eb-9358-22a7ab4453da.png)
![image](https://user-images.githubusercontent.com/26733114/103268756-0c75f300-49ef-11eb-80ea-673f034ecfd1.png)

## How to fix it?
When the function of next throwing runtime-exception, we do not need to catch it, the fixed code like this:
```
    public void retrieveAll(Collection pcs, boolean useFetchPlan)
    {
        assertIsOpen();
        ArrayList failures = new ArrayList();
        Iterator i = pcs.iterator();
        while (i.hasNext())
        {
            Object currentElem = i.next();
            try
            {
                jdoRetrieve(currentElem, useFetchPlan);
            }
            catch (RuntimeException e)
            {
                failures.add(e);
            }
        }
        if (!failures.isEmpty())
        {
            throw new JDOUserException(Localiser.msg("010038"), (Exception[]) failures.toArray(new Exception[failures.size()]));
        }
    }

```

**Comment by andyjefferson** [comment]
PR applied, since the change was innocuous. No way of seeing this since no testcase has been provided. Assumed "fixed".

**Comment by StefanXiepj** [comment]
thx, your repair is so perfect
