### ISSUE TITLE
Datanucleus will traverse collection to get all relationed filed rather than using join sql when apply retrieveAll method in JDOPersistenceManager.java 

### ISSUE THREAD

**Issue by ns7381** [datanucleus/datanucleus-api-jdo#118]
Datanucleus will traverse collection to get all relationed filed rather than using join sql when apply retrieveAll method in JDOPersistenceManager.java 
It cause retrieveAll method performance is very low

**Comment by andyjefferson** [comment]
What does that have to do with datanucleus-api-jdo? This is an API plugin. 
RDBMS handling is in the RDBMS plugin. And if raising an "issue" you have to provide a valid testcase that demonstrates something. Thx
