### ISSUE TITLE
JDO TCK 3.3.0-SNAPSHOT failing

### ISSUE THREAD

**Issue by javasmithy** [datanucleus/datanucleus-api-jdo#131]
The tck 3.3.0-SNAPSHOT fails for jdoql.conf for latest snapshot versions of datanucleus jars. The latest versions of datanucleus jars pass the tck 3.2.0 because order of execution of tests is deterministic. When they execute  concurrently in tck 3.3.0 the test fails. But they should not fail because the contains only queries no updates.

**Comment by andyjefferson** [comment]
Some test suite failing is not a bug. A bug is some functionality fails. Suggest that you debug the situation and isolate it to some actual operation. No resource here for anything other than that
