### ISSUE TITLE
Missing extensions in IndexMetaData when multiple indices are defined at class-level via @Index annotation

### ISSUE THREAD

**Issue by jgolinowski** [datanucleus/datanucleus-api-jdo#132]
### Bug report

Using multiple `@Index` annotations at class-level results in `IndexMetaData` not having any extensions. This behavior seems to be caused by not adding the extensions in [`JDOAnnotationReader`](https://github.com/datanucleus/datanucleus-api-jdo/blob/c8250f17319fe419f8fe3e6e8f431e8cf58f8af6/src/main/java/org/datanucleus/api/jdo/metadata/JDOAnnotationReader.java#L459) when the handled `AnnotationObject` is named `JDOAnnotationUtils.INDICES` (which seems to be the case for `@Indices` and more than one `@Index`).

Extensions are only added to IndexMetaData for `JDOAnnotationUtils.INDEX`, which is the case for classes with just one `@Index` annotation (see [here](https://github.com/datanucleus/datanucleus-api-jdo/blob/c8250f17319fe419f8fe3e6e8f431e8cf58f8af6/src/main/java/org/datanucleus/api/jdo/metadata/JDOAnnotationReader.java#L482)).

Adding `JDOAnnotationUtils.addExtensionsToMetaData(idxmd, idx.extensions());` in the indices-for-loop fixes the issue.

I created a simple testcase at https://github.com/jgolinowski/datanucleus-test-jdo/tree/multi-index-missing-extensions. Additionally there is another branch where I added a "fixed" `JDOAnnotationReader` (https://github.com/jgolinowski/datanucleus-test-jdo/tree/fix-multi-index-missing-extensions).

**Comment by andyjefferson** [comment]
Fixed in GitHub master. Thx for the report
