### ISSUE TITLE
Test case to reproduce an issue with executing a JDOQLType query with a result clause of candidate() or candidate(„this“)

### ISSUE THREAD

**Issue by mboapache** [datanucleus/datanucleus-api-jdo#136]
A query of the form
```
JDOQLTypedQuery<Person> query = pm.newJDOQLTypedQuery(Person.class);
query.result(false, QPerson.candidate());
query.executeList();
```
runs into an exception:
```
JDOUserException: Cannot call executeList method when query has result set to mydomain.model.QPerson@a1217f9. Call executeResultList instead.
```
Test method `testCandidate` uses `candidate()` when defining the result, 
where method `testCandidateThis` calls `candidate("this")`.

With datanucleus-api-jdo version 5.2.9 test method testCandidateThis fails with the above message. 
Call `mvn -Ddn.api_jdo.ver=5.2.9 clean compile test` to run DN 5.2.9.

With datanucleus-api-jdo version 5.2.10 both test cases fail with the above message. 
Call `mvn clean compile test` to run DN 5.2.10.

I will provide a pull request for version DN 5.2.11-SNAPSHOT with a fix. 
To run this call `mvn -Ddn.api_jdo.ver=5.2.11-SNAPSHOT clean compile test`. 
Then both test cases succeed. I could also successfully run the JDO TCK test suite with this fix.

Here is the link to the test-jdo test case: https://github.com/mboapache/test-jdo/tree/candidate-this
Here is teh link to the pull request for a fix: https://github.com/datanucleus/datanucleus-api-jdo/pull/135

**Comment by andyjefferson** [comment]
PR merged, should pass now. Thx
