### ISSUE TITLE
NullPointerException while deleting an entity

### ISSUE THREAD

**Issue by keerthikaS** [datanucleus/datanucleus-api-jdo#66]
A 'NullPointerException' is encountered while deleting an entity with a specific key. Verified that the entity exists and still an exception is thrown. Please investigate.
Attaching details.

**Code Snippet**

> 		
	{
				LOGGER.log( Level.INFO , "Using transaction to delete" );
				PersistenceManager persistenceManager = PMF.get().getPersistenceManager();
				Transaction transaction = persistenceManager.currentTransaction();
				try
					{
						transaction.begin();
						Object object = persistenceManager.getObjectById( interactionJDO , key );
						LOGGER.log( Level.INFO , "Object Retreived  :: " + object );
						InteractionJDO interaction = (InteractionJDO) object;
						LOGGER.log( Level.INFO , "Key  :: " + interaction.getUniqueIdentifier() );
						persistenceManager.deletePersistent( object );
						LOGGER.log( Level.INFO , "Object deleted" );
						transaction.commit();
					}
				catch ( JDOObjectNotFoundException e )
					{
						LOGGER.log( Level.INFO , "Entity not present" );
					}
				finally
					{
						if ( transaction.isActive() )
							{
								transaction.rollback();
							}
						persistenceManager.close();
					}

**Screenshot of stacktrace**

![transaction - delete](https://user-images.githubusercontent.com/7713033/34432027-ad02e546-ec99-11e7-9fbe-6157e0562c1f.png)

**Entity Details GAE datastore**

Entity Name : InteractionJDO
Entity Key : 24485852-6db0-48d4-b3e1-bf7fdec0322b

![image](https://user-images.githubusercontent.com/7713033/34432055-f6bf9058-ec99-11e7-9b78-c773f6609c4f.png)

**Comment by andyjefferson** [comment]
As the issue template says, you have to provide a valid testcase (and provides a template for that testcase) that reproduces a problem. The DataNucleus project provides NO SUPPORT for "Google/AppEngine"; that is Google's not ours.

**Comment by andyjefferson** [comment]
As your stack trace shows. The NPE is in Google's code. Talk to them
