### ISSUE TITLE
Federated Data Store does not query secondary data store from JDOQLTypedQuery

### ISSUE THREAD

**Issue by bkalbfus** [datanucleus/datanucleus-api-jdo#93]
If I configure a secondary data store by setting a property like
`<property name="datanucleus.datastore.other" value="datanucleus_other.properties" />`
and provide the file datanucleus_other.properties with connection information  
`javax.jdo.option.ConnectionDriverName=org.hsqldb.jdbcDriver
javax.jdo.option.ConnectionURL=jdbc:hsqldb:mem:test_other
javax.jdo.option.ConnectionUserName=sa
javax.jdo.option.ConnectionPassword=
`
And configure entity class like
`@Extension(vendorName = "datanucleus", key = "datastore", value = "other")
public class OtherPerson`

Then I am able to persist this "OtherPerson" class to the secondary data store and modify it.
But, if I create a JDOTypedQuery to get instances of this class, it does not look at the secondary datastore to get instances of this class.

Please see test case at https://github.com/bkalbfus/test-jdo

This manifested originally in my development with Apache Isis, where I opened an issue: https://issues.apache.org/jira/browse/ISIS-2020

The attached patch worked when I patched version 5.1.14 and referenced from my Apache Isis project
[datanucleus-api-jdo.zip](https://github.com/datanucleus/datanucleus-api-jdo/files/2551116/datanucleus-api-jdo.zip)

**Comment by andyjefferson** [comment]
As mentioned on Gitter, datanucleus-api-jdo has nothing at all to do with data federation; that is handled in datanucleus-core. There is 1 open issue in that project https://github.com/datanucleus/datanucleus-core/issues/18 as well as 1 recently closed issue https://github.com/datanucleus/datanucleus-core/issues/313. Your test is testing "getDatastoreConnection", not JDOQLTypedQuery. The datastore connection is specific to the operation, and that method will not provide anything of value ... always goes to primary StoreManager. Such things should be tracked via the datanucleus-core issue, hence closing this

**Comment by bkalbfus** [comment]
That assert was informational.  Comment it out to see the pragmatic assert failure to query for the persisted entity.  I will update accordingly to keep the test relevant.  I'm not trying to insist that my patch is the best route for the library - I like to keep things modular and it'd be best to let any query be analyzed and applied to relevant data stores.  The patch I am using is to allow for my use case:  query a data store for objects persisted to it.

**Comment by bkalbfus** [comment]
The test passes when I reference the latest datanucleus-core.  Thank you!
