### ISSUE TITLE
Missing isConfigurable() when entering the synchronized block

### ISSUE THREAD

**Issue by urs-ikentoo-com** [datanucleus/datanucleus-api-jdo#99]
It seems to me that  isConfigurable() should be checked again in the critical section.

https://github.com/datanucleus/datanucleus-api-jdo/blob/029d29ebc7abe851fdf1802ca7e42f823f62efb8/src/main/java/org/datanucleus/api/jdo/JDOPersistenceManagerFactory.java#L852

Assume two threads T1 and T2.
T1 runs freezeConfiguration and gets suspended just before the synchronized block (line 832)
T2 runs freezeConfiguration and enters the synchronized block
T1 resumes and gets blocked on the synchronized block
T2 exits the synchronized block
T1 resumes and since the check is missing runs the initialization a second time.

I actually have this in real world code.

**Comment by andyjefferson** [comment]
See https://github.com/datanucleus/datanucleus-api-jdo/pull/100
